import './globals.css'
import Providers from './providers'
import ThemeButton from '@/components/theme/themebutton'
import io from 'socket.io-client'

export const socket = io.connect('http://192.168.1.16:3001')

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
  return (
    <html lang='en' className='dark' style={{ colorScheme: 'dark' }}>
      <body className='dark:bg-slate-900'>
        <Providers>
          <div className='h-[5vh] w-[100-vw]'>
            <ThemeButton />
          </div>
          {children}
        </Providers>
      </body>
    </html>
  )
}
